name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
      - run: npm i -g yarn
      - run: yarn set version berry
      # - run: cat .yarnrc_patch.yml >> .yarnrc.yml
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.4
        with:
          path: |
            ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2
      - run: yarn install
      - run: yarn run clean
      - run: yarn run compile
      - run: yarn run build
      - run: yarn run prettier
      # - run: yarn test:coverage
      - run: yarn run docs
